 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/busker_profiles", type: :request do
  
  # BuskerProfile. As you add validations to BuskerProfile, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      BuskerProfile.create! valid_attributes
      get busker_profiles_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      busker_profile = BuskerProfile.create! valid_attributes
      get busker_profile_url(busker_profile)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_busker_profile_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      busker_profile = BuskerProfile.create! valid_attributes
      get edit_busker_profile_url(busker_profile)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new BuskerProfile" do
        expect {
          post busker_profiles_url, params: { busker_profile: valid_attributes }
        }.to change(BuskerProfile, :count).by(1)
      end

      it "redirects to the created busker_profile" do
        post busker_profiles_url, params: { busker_profile: valid_attributes }
        expect(response).to redirect_to(busker_profile_url(BuskerProfile.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new BuskerProfile" do
        expect {
          post busker_profiles_url, params: { busker_profile: invalid_attributes }
        }.to change(BuskerProfile, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post busker_profiles_url, params: { busker_profile: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested busker_profile" do
        busker_profile = BuskerProfile.create! valid_attributes
        patch busker_profile_url(busker_profile), params: { busker_profile: new_attributes }
        busker_profile.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the busker_profile" do
        busker_profile = BuskerProfile.create! valid_attributes
        patch busker_profile_url(busker_profile), params: { busker_profile: new_attributes }
        busker_profile.reload
        expect(response).to redirect_to(busker_profile_url(busker_profile))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        busker_profile = BuskerProfile.create! valid_attributes
        patch busker_profile_url(busker_profile), params: { busker_profile: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested busker_profile" do
      busker_profile = BuskerProfile.create! valid_attributes
      expect {
        delete busker_profile_url(busker_profile)
      }.to change(BuskerProfile, :count).by(-1)
    end

    it "redirects to the busker_profiles list" do
      busker_profile = BuskerProfile.create! valid_attributes
      delete busker_profile_url(busker_profile)
      expect(response).to redirect_to(busker_profiles_url)
    end
  end
end
